prefix : <https://purl.org/prozion/redkgr#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix afn: <http://jena.apache.org/ARQ/function#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select distinct ?person ?project ?yt ?n where {
  ?person a :Person .
  ?project a :YTChannel .
  ?project :founder ?person .
  optional {
    ?project :yt ?yt .
  } .
  optional {
    ?project :yt-n ?yt_n .
  } .
  bind(str(?yt_n) as ?n)
}
order by desc(xsd:integer(?yt_n))
